# Copyright (C) 2022, RTE (http://www.rte-france.com)
# Copyright (C) 2024, Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

unset kernel_options && declare -A kernel_options

. /usr/share/cukinia/includes/tests/kernel_hypervisor.conf

kernel_options["iommu"]="INTEL_IOMMU:y     \
                         AMD_IOMMU:y       \
                         AMD_IOMMU_V2:y    \
                         IOMMU_IOVA:y      \
                         DMAR_TABLE:y"

kernel_options["hardware"]+="X86_PKG_TEMP_THERMAL:y"

kernel_options["kvm"]="KVM:y       \
                       KVM_INTEL:y \
                       KVM_VFIO:y"

cukinia_log "$(_colorize yellow "--- Hypervisor Kernel configuration ---")"
check_kernel_configuration ${kernel_options[@]}
