# Copyright (C) 2022, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

#@TYPE: Machine
#@NAME: seapath-hypervisor
#@SOC: x86-64
#@DESCRIPTION: Machine configuration for hypervisor compatible with SEAPATH

require conf/machine/include/seapath-machine-common.inc
require conf/machine/include/seapath-kernel-x86-64.inc

