# Copyright (C) 2021, RTE (http://www.rte-france.com)
# Copyright (C) 2023 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

. /usr/share/cukinia/includes/architecture_functions
. /usr/share/cukinia/includes/clustering_functions

groups=" \
    admin \
    admincluster \
    adminsys \
    ansible \
    daemon \
    disk \
    docker \
    emergadmin \
    hugepages \
    input \
    kvm \
    libvirt \
    maint-n1 \
    maint-n3 \
    messagebus \
    nobody \
    nogroup \
    openvswitch \
    operator \
    privileged \
    qemu \
    root \
    shadow \
    shutdown \
    snmp \
    sshd \
    systemd-bus-proxy \
    systemd-journal \
    systemd-network \
    systemd-resolve \
    systemd-timesync \
    tty \
    users \
    utmp \
    vfio-net \
    video \
    wheel \
"

if is_seapath_clustering_enable; then
    groups+=" \
        ceph \
        haclient \
        livemigration \
        msmtp \
    "
fi

if is_x86; then
    groups+=" \
        sgx \
        render \
    "
fi

args="-v"
for g in ${groups}; do
    args="$args -e $g"
done

cukinia_log "$(_colorize yellow "--- check /etc/group ---")"
nb_group=$(echo $groups | wc -w)
id "SEAPATH-00033" as "/etc/group is consistent" cukinia_test $(grep $args /etc/group | wc -l)
id "SEAPATH-00034" as "/etc/group does not include extra group" cukinia_test $(cat /etc/group | wc -l) -eq $nb_group
