name: Pull Requests

on:
  # With the"pull_request" trigger, workflows triggered by PRs made from forks
  # are executed in a "safe" context without access to secrets.
  # Since we need the secret necessary to dispatch the workflow on the main
  # repo, we have to use a separate workflow using the workflow_run trigger to
  # get the necessary permissions: pr-delegation.
  # Thus, this "Pull Requests" workflow does nothing except uploading some
  # metadata so the other workflow can do the actual dispatching.
  # N.B. we cannot use the pull_request_target trigger since it does not wait
  # for approval of reviewers, which is a big security issue.

  pull_request:
    branches:
      - scarthgap
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - .github/**/*

jobs:
  # It can look crazy but the workflow_run trigger does not expose data about
  # the PR of the initial workflow _for forked repositories_.
  # (https://github.com/orgs/community/discussions/25220)
  # Thus, we do this ugly thing of putting it in an artifact to consume it
  # in the next workflow.
  export-pr-metadata:
    name: "Export PR metadata"
    env:
      PR_METADATA_FILE: pr_metadata.json
    runs-on: ["ubuntu-slim"]
    steps:
      - name: Create metadata file
        run: |
          cat <<EOF > ${{ env.PR_METADATA_FILE }}
          {
            "pr_number": ${{ github.event.pull_request.number }},
            "pr_sha": "${{ github.sha }}",
            "pr_base_ref": "${{ github.base_ref }}"
          }
          EOF

      - name: Upload metadata artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: "${{ env.PR_METADATA_FILE }}"
          retention-days: 1
