name: Build on push

on:
  push:
    branches:
      - wrynose
    paths-ignore:
      - .github/**/*
  # We add the manual dispatch trigger so we can test our pipelines
  workflow_dispatch:

jobs:
  delegate-main-repo:
    name: Delegate to the main repository
    # We don't need a self-hosted runner here since this workflow will only
    # do network calls to the GitHub API.
    # The only problem is that it might run for a long time (same time as the
    # called build workflow on the main repo) so we might exceed usage limit
    # of the free hosted runners (which is a few hours).
    # In this case, it might be better to register a new self-hosted runner
    # specifically for doing this kind of lightweight workloads.
    # For now we use public runners. For those workloads, ubuntu-slim would be
    # perfect since the task is very lightweight. However, as explained in
    # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#usage-limits,
    # slim runners have a fixed 15-minutes job timeout which makes them
    # unusable in our case. Thus, we use a classic runner.
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Create a token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-actions: write

      - name: Invoke the build workflow
        id: delegation
        uses: benc-uk/workflow-dispatch@70455941930e5212314c10c0e38ec94986096618
        with:
          workflow: push.yml
          repo: "${{ vars.MAIN_REPO }}"
          # the branch names are the same between this repo and the main one
          ref: "${{ github.ref_name }}"
          token: "${{ steps.app-token.outputs.token }}"
          wait-for-completion: true
          wait-timeout-seconds: 21600 # 6 hours
          sync-status: true
          inputs: |
            {
              "origin_repository": "${{ github.repository }}",
              "origin_sha": "${{ github.sha }}",
              "origin_run_id": "${{ github.run_id }}"
            }

      - name: Display notice
        if: always()
        run: |
          echo "::notice::The Build workflow was delegated to the main repository. See details at ${{ steps.delegation.outputs.runUrlHtml }}"
